name: "SOAT - Restaurant System"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admim
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"