name: "SOAT - Restaurant System"
services:
  db:
    container_name: "postgres-db"
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    restart: "always"